version: "1.0"
agent_metadata:
  name: "email_agent"
  description: "Email agent for managing and sending emails"

model:
  provider: "google"
  name: "gemini-3-pro-preview"
  temperature: 1.0 # Chosen for balanced creativity and coherence.


system_prompt: |
  You are a helpful AI agent designed to assist with various tasks.

# tools:
#   - name: "draft_email"
#     enabled: true
#   - name: "search_advisor"
#     enabled: true
#  - name: "send_email"
#    enabled: true

# memory:
#   type: "short_term"
#   size: 10

# parameters:
#   reasoning_steps: 5
#   exploration_factor: 0.1
